Python/crossfire/crossfire/client.py, Python/crossfire/crossfire/errors.py, Python/crossfire/tests/conftest.py, Python/crossfire/tests/test_client.py
Esse PR cria um cliente para acesso da API. Ele abstrai a parte de autenticação e sempre retorna uma chave válida (dado que as variáveis de ambiente `FOGOCRUZADO_EMAIL` e `FOGOCRUZADO_PASSWORD` estejam configuradas corretamente):
```python
>>> from crossfire.client import Client
>>> client = Client()
>>> client.token
'ey…'
```
Também, o cliente controla a validade da chave e pede uma nova caso a atual tenha expirado.
Esse PR **não** utiliza esse cliente _ainda_. A ideia é em futuros PRs:
=> Crie cliente para uso da API

Python/crossfire/README.md, Python/crossfire/poetry.lock, Python/crossfire/pyproject.toml
Esse PR simplifica as verificações de código. Ao invés de 3 comandos (`black .`, `ruff .` e `pytest`) o PR configura o `pytest` para executar automaticamente o Ruff e o Black. Sendo assim, só precisamos de `pytest` sendo executado.
=> Executa Black e Ruff junto com os testes

Python/crossfire/crossfire/client.py, Python/crossfire/tests/test_client.py
Adiciona a possibilidade de passar as credenciais `email` e `password`, para autentiação do [`Client`](), a partir de named_keys, sobreescrevendo as credenciais definidas por variáveis de ambiente.
=> adiciona kwargs ao Client() permitindo sobreescrever a variavel de ambiente com named_keys

Python/crossfire/crossfire/client.py, Python/crossfire/crossfire/fogocruzado_utils.py, Python/crossfire/tests/test_client.py, Python/crossfire/tests/test_crossfire.py
Esse PR adiciona o _endpoint_ `states` ao cliente da API:hon
```python
>>> from crossfire.client import Client
>>> client = Client()
>>> states = client.states()
>>> states
id            name
0  b112ffbe-17b3-4ad0-8f2a-2038745d1d14  Rio de Janeiro
1  813ca36b-91e3-4a18-b408-60b27a1942ef      Pernambuco
2  d3a9b545-7056-4dc6-9b68-ce320c9edffc           Bahia
>>> 
```
E adiciona a opção para _não_ utilizar o Pandas caso não seja desejado:
```python
>>> from crossfire.client import Client
>>> client = Client()
>>> states = client.states(format='dict')
>>> states
[{'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14', 'name': 'Rio de Janeiro'}, {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef', 'name': 'Pernambuco'}, {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc', 'name': 'Bahia'}]
```
No caminho:
* …
=> Adiciona a chamada de UF no cliente da API

Python/crossfire/tests/test_occurences.py
Esse PR sugere dois testes básicos para colaborar com o #31 ao estilo TDD — seguir a direção que esses testes sugerem ajudaria no progresso da implementação.
(Repare que o PR adiciona o código à `add_client_occurences` ao invés de `master` 😉 )
=> Cria testes para a classe `Occurences`

Python/crossfire/crossfire/client.py, Python/crossfire/tests/test_client.py
Conforme mencionado na issue #36 : este PR altera os métodos `Client.states()` e `Client.cities() adicionando uma abstração que desconsidera a informação de paginação.
Com isso usuário final poderá usar-los sem se preocupar em criar um objeto para paginação.
=> Altera `Client.states()` e `Client.cities()` para não retornar informação sobre paginação

Python/crossfire/crossfire/client.py, Python/crossfire/crossfire/occurrences.py, Python/crossfire/tests/test_occurences.py
Este PR depende do #31 e fecha #40 , caso aprovado.
Adiciona novos testes validando o uso dos parâmetros de `Occurrences`:
Antes estávamos testando `Occurrences` com os parâmetros obrigatórios (`id_state`).
Foi aidiconado um testa validando o efeito no uso do parâmetros `id_cities` na URL chamada elo `client.get`.
=> Add occurrences test parameters

Python/crossfire/crossfire/occurrences.py, Python/crossfire/tests/test_occurences.py
Isso facilita o uso, evitando a necessidade de `break` quando não queremos todos os registros — por exemplo, ao invés de:
```python
ocorências = []
for occorência in Occurences(id_state=42):
ocorrências.append(ocorrência)
if len(ocorrências) == 100:
break
```
Podemos ter apenas:
```python
ocorrências = tuple(Occurences(id_state=42, limit=100))
```
=> Adiciona opção de limite para consulta de ocorrências

Python/crossfire/crossfire/occurrences.py
Esse código, na minha opinião, é muito mais complexo do que precisamos:
```python
self.params = {
key: value
for key, value in {"idState": id_state, "idCities": id_cities}.items()
if value
}
```
Na sequência:
* Criamos um dicionário com `idStates` e `idCities`
* Iteramos nesse dicionário transformando cada par em uma tupla
* Comparamos se cada valor é `None` (ou `not False`) ou não
* Criamos um novo dicionário
Dado que, `id_state` é um argumento obrigatório na classe e nunca vai ser `None`, tudo que essa lógica está fazendo é garantindo que só adicionamos `id_city` se não for `None`. Isso pode ser feito com um simples `if`:
```python
self.params = {"idState": id_state}
if id_city:
```
=> Simplifica lógica de criação dos parâmetros na classe de ocorrências

Python/crossfire/crossfire/load_data.py, Python/crossfire/poetry.lock, Python/crossfire/pyproject.toml
* Não encontrei uso da `DateTime`
* Uso da `python-dateutils` era para algo simples de ser feito com a biblioteca padrão
Então sugiro remover as duas.
=> Cleans up: remove unused dependencies

Python/crossfire/crossfire/occurrences.py, Python/crossfire/crossfire/parser.py, Python/crossfire/tests/test_occurences.py, Python/crossfire/tests/test_parser.py
Parte da #46
Para podermos fazer mais reequisições em paralelo, precisamos saber quantas páginas temos que requisitar. Esse PR facilita isso expondo outros dados do `pageMeta` além do `hasNextPage`.
=> Expõe todas as metainformações de uma consulta à API

Python/crossfire/crossfire/client.py, Python/crossfire/tests/test_client.py
Parte de #46 
Esse limite ainda não é utilizado, mas é parte integrante da melhoria de performance mencionada na _issue_. Pode ser inderido depois, mas creio que PRs menores facilitem a revisão.
=> Adiciona configuração para limitar número de requisicões paralelas

Python/crossfire/poetry.lock, Python/crossfire/pyproject.toml
Atualmente o `python-decouple` está no grupo (legado) de dependências de desenvolvimento. Isso é um erro, dado que utilizamos a dependência no fluxo normal do `Client` — ou seja, não apenas em desenvolvimento. O _bug_ seria que ao instalar o pacote via `pip` teríamos um erro na importação desse pacote ao iniciar um cliente.
Esse PR move a dependência para o grupo “dependências” (não apenas “dependências de desenvolvimento”).
=> Bug fix: Torna `python-decouple` dependência do projeto

Python/crossfire/crossfire/occurrences.py, Python/crossfire/tests/test_occurences.py
Este PR adiciona o parâmetro `type_occurrence` à classe `Occurrence`. Por padrão, o valor é `all`. Como sugerido em #39 (de tomar como exemplo o `format`), criei uma contacte com os valores possíveis. O init de Occurrences, valido se o `type_occurrence` está listado na constante. Caso contrário, levanta um `TypeOccurrenceError` e, na mensagem informamos quais seriam os valores possíveis.
Com isso alguns testes relacionado a `OCcurrence tiveram que ser atualizados. E foi criado um teste para validar o erro quando o parâmetro informado não for contemplado na constante...
=> add type_occurrence parameter on Occurrence

Python/crossfire/crossfire/client.py
Existe um erro no código atual que impede chmarmos duas vezes uma função que utiliza o cliente `asyncio`.
```python
from crossfire.client import Client
client = Client()
client.states()  # essa funcionaria
client.states()  # essa falharia
```
Isso porquê o `async.run` encerra o _loop_. Então esse PR sugere substituir o `async.run` pela combinação
* pegar o _event loop_ atual
* executar a corotina nesse _event loop_
=> Corrige erro no _loop_ utilizado pelo `asyncio`

Python/crossfire/crossfire/parser.py, Python/crossfire/tests/test_parser.py
Depende do #58 
Quando a API retorna HTTP Status 429 (TOO Many Requests), capturamos esse status e geramos um erro específico. Isso vai permitir uma espera e tentar novamente a mesma requisição no futuro.
=> Gera erro para status HTTP 429 Too Many Requests

Python/crossfire/crossfire/occurrences.py, Python/crossfire/tests/test_occurences.py
Esse PR cria um acumulador para guardar todas as ocorrências (não importando se são uma lista de dicionáro, ou um _dataframe_ do Pandas ou GeoPandas). Como exemplo, dos testes:
```python
accumulator = Accumulator()
accumulator.merge([1])
accumulator.merge([2], [3])
accumulator()  # [1, 2, 3]
```
E funciona igual com `DataFrame` e `GeoDataTrame`:
```python
accumulator = Accumulator()
accumulator.merge(DataFrame([{"a": 1}]))
accumulator.merge(DataFrame([{"a": 2}]), DataFrame([{"a": 3}]))
```
```python
accumulator = Accumulator()
accumulator.merge(GeoDataFrame([{"a": 1}]))
accumulator.merge(GeoDataFrame([{"a": 2}]), GeoDataFrame([{"a": 3}]))
```
Esse `Accumulator` será utilizado para agregar os resultados de diversas requições (uma para cada página) com o cliente `async`.
=> Cria um “acumulador” para salvar os resultados de diversar requisições

Python/crossfire/crossfire/client.py, Python/crossfire/tests/test_client.py
Vamos reimplementar em outro PR utilizando `asyncio.Sempahore`. Isso ajuda a manter a verificação SSL sem problemas de concorrência.
=> Remove o limite de conexões paralelas

Python/crossfire/crossfire/client.py, Python/crossfire/crossfire/occurrences.py, Python/crossfire/poetry.lock, Python/crossfire/pyproject.toml, Python/crossfire/tests/conftest.py, Python/crossfire/tests/test_client.py, Python/crossfire/tests/test_occurences.py
Examplo de uso da nova implementação:
```python
In [1]: from crossfire.client import Client
In [2]: client = Client()
In [3]: client.states()
Out[3]: 
[{'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14', 'name': 'Rio de Janeiro'},
{'id': '813ca36b-91e3-4a18-b408-60b27a1942ef', 'name': 'Pernambuco'},
{'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc', 'name': 'Bahia'},
{'id': '2a98a020-3815-45d7-a6f6-6de2119eba8b', 'name': 'Para'}]
In [4]: client.occurrences('813ca36b-91e3-4a18-b408-60b27a1942ef')
```
Isso cria uma barra de progresso e carrega todas as ocorrências dessa UF da API.
=> Implementa requisições assícronas para obter mais ocorrências, mais rápido

Python/crossfire/crossfire/clients/__init__.py, Python/crossfire/crossfire/clients/occurrences.py, Python/crossfire/crossfire/errors.py, Python/crossfire/crossfire/parser.py, Python/crossfire/tests/test_client.py, Python/crossfire/tests/test_parser.py
Remove a lógica de gerenciamento da requisição, movendo-a para o `Client`.
Closes #67
=> Refatora `parse_response`

.github/workflows/github-actions.yml, Python/crossfire/poetry.lock, Python/crossfire/pyproject.toml
Utilizávamos como dependência o Pandas na versão 2.1.0, que dependia do Numpy 1.25.2, que não é compatível com Python 3.12 (ver #70).
Esse PR:
* Muda versão mínima do Pandas para 2.1.1 (que eleva a versão mínima do Numpy para uma posterior ao 1.25.2 e compatível com Python 3.12)
* Gera o `poetry.lock` atualizado
* Executa a CI com todas as versões (major) do Python entre 3.9 e 3.12 
* Marca o pacote como compatível com todas as versões do Python entre 3.9 e 3.12
Closes #71
=> Torna o pacote compatível com Python 3.12

crossfire/__init__.py
Adiciona `AsyncClient` e `Client` ao `__all__` de `crossfire.__init__.py`, conforme proposta na issue #76
=> adiciona AsyncClient e Client em crossfire.__init__

CONTRIBUTING.md, crossfire/clients/__init__.py, crossfire/clients/occurrences.py, crossfire/logger.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/test_client.py, tests/test_init.py, tests/test_occurrences_client.py, tests/test_parser.py
Na versão mais nova, o Ruff já cuida de formatação (papel do Black) e de organizar os imports (papel do isort).
As mudanças de formatação foram automáticas pela lógica do Ruff (um pouco distinta do Black), mas não interferem na lógica do código.
=> Substitui Black e isort pelo Ruff

crossfire/clients/__init__.py
@cuducos li a documentação e entendi como aplicar a formatação do ruff.
Ao fazer o merge, não prestei atenção que o seu PR não tinha (claro) os ultimos commits aceitos por PR.
Por isso abri uma branch nova para aplicar a formatação do ruff.
[agora, sim]
=> aplica ruff format em clients.__init__

crossfire/clients/occurrences.py
[Como comentado](https://github.com/FelipeSBarros/crossfire/issues/85#issuecomment-1845541654):
> O cliente de ocorrências tem um método page(self, number) que, como o nome do argumento diz, espera um número de página para fazer a requisição.
>
> Acontece que quando a requisição falha, e vamos tentar novamente, estamos passando a URL para tentar novamente (ao invés do número da página para tentar novamente)
=> Corrige chamada do “tentar novamente” quando a requisição de uma ocorrência falha

README.md, crossfire/clients/__init__.py, crossfire/clients/occurrences.py, crossfire/errors.py, tests/test_client.py, tests/test_occurrences_client.py
@cuducos aproveitei o embalo e comecei a trabalhar no parâmetro de data para o end point occurrences, conforme mencionado em #83 .
=> Add date parameter occurrences

README.md
Só após publicar o módulo é que percebi que deixamos passar um título do README em português.
Fiz uma tradução livre (e acho que talvez seja suficiente...).
Atualizações deste tipo, demandam atualização no pacote publicado e, portanto na versão do mesmo?
=> update README translate title in pt-br to en

crossfire/__init__.py, tests/test_init.py
@cuducos I believe that the changes done un this commit solve the prolems with `initial` and `final_date` on `occurrences`  available through  `crossfire.__init__`, problem from issue #89
=> update crossfire.__init__ occurrences adding initial_ and final_date

crossfire/clients/occurrences.py, tests/test_occurrences_client.py
Started trying to get the bug (#90 ) by testing it, 
But seems that I still need to understand how to test it.
my line of thinking is:
I need to confirm if, the `format` parameter on `Occurrence` class is passed to `client.get` method, which is an instance of `Client` passed in `Occurrences` instatitation;
So, I believe that I can use `patch.object` to mock `AsyncClient.get` method so I can assert f its been called with the right parameters.
But, as `client.get` should be instantiated, I thin I should mock the config, also.
But the test says that the  "expected call not found".
Am I write? Am I misisng something?
=> fixing Occurrences `format`parameter bug

tests/test_occurrences_client.py
Instead of using custom mocks, this PR suggests using the existing fixtures to run the test implemented in #91
=> Simplifies occurrences with format test

pyproject.toml
@cuducos , after the bugfix on `Occurrences`, I understand that we should update the module version, build and publish it again so it is available to all thru pypi.
After taking a quick look at the [Semantic Versioning](https://semver.org/) I believe that the new version is a `PATCH` update from `v1.0.0`. So I updated the `pyproject.toml` to `v1.0.1`.
=> update version 1.0.1 after bug fix on Occurrences

crossfire/parser.py, tests/test_parser.py
@cuducos either I neglected to review the end point of [Occurrences](https://api.fogocruzado.org.br/docs/endpoint/occurrences) (very likely) or they updated the name of the latitude column (`latitude_ocorrencia` for `latitude` and `longitude_ocorrencia` for `longitude`);
In this PR I update the  expected names of the `latitude` and `longitude` columns.
=> Fix lat lon Occurrences column name

crossfire/__init__.py, tests/test_flatten.py
@cuducos , during the construction of the `flatten` function I have wrongly added some "column name" (dict keys, for now) in the `NESTED_COLUMNS` constant.
I did it by reading the API documentation. But once finished the PR #100 I did some test with real data an realized that some "columns" are not nested. I created a issue #101 about it. (sorry, I should have tested before closing the PR... I will try to be more careful next time)
Today I fixed it removing those "columns names" and added some other. This time I have tested with occurrences from the second semester of 2022.
```python
from crossfire import AsyncClient, flatten
client = AsyncClient()
states_dict, _ = await client.states(format="dict")
states_df, _ = await client.states(format="df")
cities_rj, _ = await …
```
=> Fix nested columns constant

crossfire/clients/__init__.py, poetry.lock, pyproject.toml, tests/test_client.py
Fixes `asyncio` error when running in environments with another loop running (e.g. Colab).
Long story short, the added library explains the underlying problem:
> By design asyncio [does not allow](https://github.com/python/cpython/issues/66435) its event loop to be nested […]
>
> This module patches asyncio to allow nested use of asyncio.run and loop.run_until_complete.
=> Fixes asyncio loop issue on Colab (and other situations where a loop is already running)
